# permissions to do viewer etcdproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcdproxy-viewer-role
rules:
- apiGroups:
  - etcd.camelcasenotation.io
  resources:
  - etcdproxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - etcd.camelcasenotation.io
  resources:
  - etcdproxies/status
  verbs:
  - get
