# permissions to do edit etcdproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcdproxy-editor-role
rules:
- apiGroups:
  - etcd.camelcasenotation.io
  resources:
  - etcdproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - etcd.camelcasenotation.io
  resources:
  - etcdproxies/status
  verbs:
  - get
  - patch
  - update
